[tool.black]
line-length = 120
target-version = ['py314']

[tool.flake8]
max-line-length = 120
extend-ignore = """
    E203
    E402
"""

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing --cov-config=.coveragerc"
